Fix commits and linter error detection

diff --git a/.github/workflows/prettier-pr.yml b/.github/workflows/prettier-pr.yml
--- a/.github/workflows/prettier-pr.yml
+++ b/.github/workflows/prettier-pr.yml
@@ -33,13 +33,18 @@ jobs:
 
           # Intentar hacer commit
           git add .
-          git commit -m "🚀 Auto-format code and linting check"
-          COMMIT_STATUS=$?
 
-          if [ $COMMIT_STATUS -eq 0 ]; then
-            echo "✅ Commit checks OK, continuing commiting"
+          if git commit -m "🚀 Auto-format code and linting check"; then
+            echo "✅ Commit successful, pushing and pipeline..."
             git push
           else
-            echo "❌ Commit with errors, aborting"
-            exit 1
+            COMMIT_STATUS=$?
+            # if commit is empty we go out successfully
+            if [ $COMMIT_STATUS -eq 1 ]; then
+              echo "⚠️ Nothing to commit, continue pipelining"
+              exit 0
+            else
+              echo "❌ Checks failed, aborting pipeline"
+              exit 1
+            fi
           fi
